title: Communal Recipes
description: A recipe container
theme: just-the-docs

url: https://casualchaos.github.io/comm-recipes

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
#  - jekyll/tagging
#  - jekyll-tagories

sass:
  quiet_deps: true

# tag_page_layout: tag_page
# tag_page_dir: tags