title: Communal Recipes
description: A recipe container
theme: just-the-docs

url: https://casualchaos.github.io/comm-recipes

favicon_ico: "/assets/images/favicon.ico"

back_to_top: true
back_to_top_text: "Back to top"


# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
  - jekyll-target-blank



